<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-13T14:50:26 IST" name="Suite" finished-at="2024-03-13T14:51:05 IST" duration-ms="39190">
    <groups>
    </groups>
    <test started-at="2024-03-13T14:50:26 IST" name="Test" finished-at="2024-03-13T14:51:05 IST" duration-ms="39190">
      <class name="TestCases.LoginTest">
        <test-method is-config="true" signature="openapplication()[pri:0, instance:TestCases.LoginTest@77c2494c]" started-at="2024-03-13T14:50:26 IST" name="openapplication" finished-at="2024-03-13T14:50:44 IST" duration-ms="17670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapplication -->
        <test-method signature="logintest(java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTest@77c2494c]" started-at="2024-03-13T14:50:44 IST" name="logintest" data-provider="dp" finished-at="2024-03-13T14:50:57 IST" duration-ms="12718" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[zxc12345@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[zxc@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at TestCases.LoginTest.logintest(LoginTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method signature="logintest(java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTest@77c2494c]" started-at="2024-03-13T14:50:57 IST" name="logintest" data-provider="dp" finished-at="2024-03-13T14:51:05 IST" duration-ms="8332" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[buyer.ncrypted@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method is-config="true" signature="CloseApplication()[pri:0, instance:TestCases.LoginTest@77c2494c]" started-at="2024-03-13T14:51:05 IST" name="CloseApplication" finished-at="2024-03-13T14:51:05 IST" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseApplication -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
